# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 801, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidgetClient = QtGui.QTableWidget(self.tab)
        self.tableWidgetClient.setGeometry(QtCore.QRect(10, 60, 421, 351))
        self.tableWidgetClient.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableWidgetClient.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetClient.setObjectName(_fromUtf8("tableWidgetClient"))
        self.tableWidgetClient.setColumnCount(3)
        self.tableWidgetClient.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetClient.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetClient.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetClient.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetClient.setHorizontalHeaderItem(2, item)
        self.tableWidgetClient.horizontalHeader().setDefaultSectionSize(137)
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(443, 60, 16, 381))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 781, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.button_FetchClient = QtGui.QPushButton(self.tab)
        self.button_FetchClient.setGeometry(QtCore.QRect(450, 10, 101, 31))
        self.button_FetchClient.setObjectName(_fromUtf8("button_FetchClient"))
        self.label_ClientPhoto = QtGui.QLabel(self.tab)
        self.label_ClientPhoto.setGeometry(QtCore.QRect(470, 60, 141, 161))
        self.label_ClientPhoto.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_ClientPhoto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ClientPhoto.setObjectName(_fromUtf8("label_ClientPhoto"))
        self.button_NewClient = QtGui.QPushButton(self.tab)
        self.button_NewClient.setGeometry(QtCore.QRect(570, 10, 111, 31))
        self.button_NewClient.setObjectName(_fromUtf8("button_NewClient"))
        self.button_DeleteClient = QtGui.QPushButton(self.tab)
        self.button_DeleteClient.setGeometry(QtCore.QRect(700, 10, 91, 31))
        self.button_DeleteClient.setObjectName(_fromUtf8("button_DeleteClient"))
        self.label_NameClient = QtGui.QLabel(self.tab)
        self.label_NameClient.setGeometry(QtCore.QRect(470, 245, 47, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_NameClient.setFont(font)
        self.label_NameClient.setObjectName(_fromUtf8("label_NameClient"))
        self.lineEdit_NameClient = QtGui.QLineEdit(self.tab)
        self.lineEdit_NameClient.setGeometry(QtCore.QRect(520, 240, 261, 31))
        self.lineEdit_NameClient.setObjectName(_fromUtf8("lineEdit_NameClient"))
        self.lineEdit_Client = QtGui.QLineEdit(self.tab)
        self.lineEdit_Client.setGeometry(QtCore.QRect(10, 10, 421, 31))
        self.lineEdit_Client.setObjectName(_fromUtf8("lineEdit_Client"))
        self.label_SexClient = QtGui.QLabel(self.tab)
        self.label_SexClient.setGeometry(QtCore.QRect(471, 350, 33, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_SexClient.setFont(font)
        self.label_SexClient.setObjectName(_fromUtf8("label_SexClient"))
        self.radioButton_M = QtGui.QRadioButton(self.tab)
        self.radioButton_M.setGeometry(QtCore.QRect(520, 350, 82, 17))
        self.radioButton_M.setChecked(True)
        self.radioButton_M.setObjectName(_fromUtf8("radioButton_M"))
        self.radioButton_F = QtGui.QRadioButton(self.tab)
        self.radioButton_F.setGeometry(QtCore.QRect(610, 350, 82, 17))
        self.radioButton_F.setObjectName(_fromUtf8("radioButton_F"))
        self.label_NameClient_2 = QtGui.QLabel(self.tab)
        self.label_NameClient_2.setGeometry(QtCore.QRect(470, 295, 47, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_NameClient_2.setFont(font)
        self.label_NameClient_2.setObjectName(_fromUtf8("label_NameClient_2"))
        self.lineEdit_CPFClient = QtGui.QLineEdit(self.tab)
        self.lineEdit_CPFClient.setGeometry(QtCore.QRect(520, 290, 261, 31))
        self.lineEdit_CPFClient.setObjectName(_fromUtf8("lineEdit_CPFClient"))
        self.button_Picture = QtGui.QPushButton(self.tab)
        self.button_Picture.setGeometry(QtCore.QRect(620, 190, 71, 31))
        self.button_Picture.setObjectName(_fromUtf8("button_Picture"))
        self.button_Save = QtGui.QPushButton(self.tab)
        self.button_Save.setGeometry(QtCore.QRect(690, 410, 91, 31))
        self.button_Save.setObjectName(_fromUtf8("button_Save"))
        self.button_Cancel = QtGui.QPushButton(self.tab)
        self.button_Cancel.setEnabled(False)
        self.button_Cancel.setGeometry(QtCore.QRect(594, 410, 81, 31))
        self.button_Cancel.setObjectName(_fromUtf8("button_Cancel"))
        self.progressBar_Client = QtGui.QProgressBar(self.tab)
        self.progressBar_Client.setGeometry(QtCore.QRect(10, 420, 421, 23))
        self.progressBar_Client.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar_Client.setProperty("value", 0)
        self.progressBar_Client.setTextVisible(False)
        self.progressBar_Client.setInvertedAppearance(False)
        self.progressBar_Client.setObjectName(_fromUtf8("progressBar_Client"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 121))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("images/banner.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 580, 801, 31))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("images/bottom.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label.raise_()
        self.tabWidget.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_Client)
        MainWindow.setTabOrder(self.lineEdit_Client, self.tableWidgetClient)
        MainWindow.setTabOrder(self.tableWidgetClient, self.button_FetchClient)
        MainWindow.setTabOrder(self.button_FetchClient, self.button_NewClient)
        MainWindow.setTabOrder(self.button_NewClient, self.button_DeleteClient)
        MainWindow.setTabOrder(self.button_DeleteClient, self.button_Picture)
        MainWindow.setTabOrder(self.button_Picture, self.lineEdit_NameClient)
        MainWindow.setTabOrder(self.lineEdit_NameClient, self.lineEdit_CPFClient)
        MainWindow.setTabOrder(self.lineEdit_CPFClient, self.radioButton_M)
        MainWindow.setTabOrder(self.radioButton_M, self.radioButton_F)
        MainWindow.setTabOrder(self.radioButton_F, self.button_Cancel)
        MainWindow.setTabOrder(self.button_Cancel, self.button_Save)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "McDonald\'s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Pedidos", None))
        item = self.tableWidgetClient.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome", None))
        item = self.tableWidgetClient.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sexo", None))
        item = self.tableWidgetClient.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF", None))
        self.button_FetchClient.setText(_translate("MainWindow", "Buscar", None))
        self.label_ClientPhoto.setText(_translate("MainWindow", "Foto do Cliente", None))
        self.button_NewClient.setText(_translate("MainWindow", "Novo Registro", None))
        self.button_DeleteClient.setText(_translate("MainWindow", "Excluir", None))
        self.label_NameClient.setText(_translate("MainWindow", "Nome:", None))
        self.lineEdit_Client.setPlaceholderText(_translate("MainWindow", "Digite o nome do cliente", None))
        self.label_SexClient.setText(_translate("MainWindow", "Sexo:", None))
        self.radioButton_M.setText(_translate("MainWindow", "Masculino", None))
        self.radioButton_F.setText(_translate("MainWindow", "Feminino", None))
        self.label_NameClient_2.setText(_translate("MainWindow", "CPF:", None))
        self.lineEdit_CPFClient.setPlaceholderText(_translate("MainWindow", "Ex.: 123.456.789-00", None))
        self.button_Picture.setText(_translate("MainWindow", "Procurar...", None))
        self.button_Save.setText(_translate("MainWindow", "Salvar", None))
        self.button_Cancel.setText(_translate("MainWindow", "Cancelar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Clientes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Funcionários", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Lanches", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bebidas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Combos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Sobre", None))
